accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'
urlpatterns = [
  url(r'^(?P<pk>[0-9]+)/?$', views.DetailView.as_view(), name='detail'),
  url(r'^(?P<account_id>[0-9]+)/edit/?$', views.edit, name='edit'),
  url(r'^(?P<account_id>[0-9]+)/update/?$', views.update, name='update'),
  url(r'^new/?$', views.new, name='new'),
  url(r'^create/?$', views.create, name='create'),
  url(r'^create_transaction/?$', views.create_transaction, name='create_transaction'),
]

envelopes/urls.py
from django.conf.urls import url

from . import views

app_name = 'envelopes'
urlpatterns = [
  url(r'^(?P<pk>[0-9]+)/?$', views.DetailView.as_view(), name='detail'),
  url(r'^(?P<envelope_id>[0-9]+)/edit/?$', views.edit, name='edit'),
  url(r'^(?P<envelope_id>[0-9]+)/update/?$', views.update, name='update'),
  url(r'^new/?$', views.new, name='new'),
  url(r'^create/?$', views.create, name='create'),
  url(r'^create_transaction/?$', views.create_transaction, name='create_transaction'),
  url(r'^refill/?$', views.refill, name='refill'),
]

home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
  url(r'^create_transaction/$', views.create_transaction, name='create_transaction'),
  url(r'^refill/$', views.refill, name='refill'),
  url(r'^', views.home, name='home'),
]

money/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from accounts import views as account_views
from envelopes import views as envelope_views
from transactions import views as transaction_views

urlpatterns = [
  url(r'^login/$', auth_views.login, {'template_name': 'shared/login.html'}, name='login'),
  url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
  url(r'^accounts/', include('accounts.urls')),
  url(r'^accounts', account_views.IndexView.as_view(), name='accounts'),
  url(r'^envelopes/', include('envelopes.urls')),
  url(r'^envelopes', envelope_views.IndexView.as_view(), name='envelopes'),
  url(r'^transactions/', include('transactions.urls')),
  url(r'^transactions', transaction_views.IndexView.as_view(), name='transactions'),
  url(r'^admin/', admin.site.urls),
  url(r'^home/', include('home.urls')),
  url(r'^', include('home.urls')),
]

transactions/urls.py
from django.conf.urls import url

from . import views

app_name = 'transactions'
urlpatterns = [
  url(r'^create/?$', views.create, name='create'),
]

transactions/models.py
from django.db import models
from accounts.models import Account

class Transaction(models.Model):
  account  = models.ForeignKey(Account, on_delete=models.CASCADE)
  envelope = models.ForeignKey('envelopes.Envelope', on_delete=models.CASCADE, null=True, default=None)
  date     = models.DateField()
  amount   = models.DecimalField(default=0, max_digits=8, decimal_places=2)

  class Meta:
    ordering = ['-date']

  def __str__(self):
    return self.date.isoformat()

  def save(self, *args, **kwargs):
    result = super(Transaction, self).save(*args, **kwargs)
    if self.envelope:
      self.envelope.calculate_transaction_velocity()

    return result

transactions/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from .models import Transaction
from accounts.models import Account
from envelopes.models import Envelope

class IndexView(LoginRequiredMixin, generic.ListView):
  template_name = 'transactions/index.html'
  context_object_name = 'all_transactions'

  def get_queryset(self):
    return Transaction.objects.filter(account__user_id=self.request.user.id).order_by('-date')

  def get_context_data(self, **kwargs):
    context = super(IndexView, self).get_context_data(**kwargs)
    context['all_accounts'] = Account.objects.filter(user_id=self.request.user.id).order_by('name')
    context['all_envelopes'] = Envelope.objects.filter(user_id=self.request.user.id).order_by('name')
    return context

@login_required
def create(request):
  account  = get_object_or_404(Account, pk=request.POST['account_id'])
  amount   = request.POST['amount']
  envelope = None
  if isinstance(request.POST['envelope_id'], int):
    envelope = get_object_or_404(Envelope, pk=request.POST['envelope_id'])

  if 'subtract' in request.POST:
    amount = float(amount) * -1.00

  try:
    transaction = Transaction(account=account, envelope=envelope, date=request.POST['date'], amount=amount)
  except (KeyError):
    messages.add_message(request, messages.ERROR, 'Something squiffy happened.')
    return render(request, 'transactions/index.html')
  else:
    transaction.save()
    messages.add_message(request, messages.SUCCESS, 'Transaction added.')
    return HttpResponseRedirect(reverse('transactions'))

transactions/templates/transactions/index.html
{% extends 'shared/base.html' %}
{% block title %} transactions {% endblock %}
{% load static %}
{% load currency %}

{% block main %}
  <h1>all transactions</h1>
  {% if all_transactions %}
  <table>
    <thead>
      <tr>
        <th>date</th>
        <th>account</th>
        <th>envelope</th>
        <th class="txt--right">amount</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in all_transactions %}
      <tr>
        <td>{{ transaction }}</td>
        <td><a href="{% url 'accounts:detail' transaction.account_id %}">{{ transaction.account }}</a></td>
        <td>
          {% if transaction.envelope_id %}
          <a href="{% url 'envelopes:detail' transaction.envelope_id %}">{{ transaction.envelope }}</a>
          {% else %}
          -
          {% endif %}
        </td>
        <td class="txt--right {% if transaction.amount > 0 %}fnt--green{% else %}fnt--red{% endif %}">{{ transaction.amount|currency }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}
{% endblock %}

{% block aside %}
  <aside class="grd-row-col-2-6">
    <form action="{% url 'transactions:create' %}" method="post" class="brdr--light-gray">
      {% include 'shared/partials/transaction_form.html' with all_accounts=all_accounts all_envelopes=all_envelopes %}
    </form>
  </aside>
{% endblock %}