accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'
urlpatterns = [
  url(r'^(?P<pk>[0-9]+)/?$', views.DetailView.as_view(), name='detail'),
  url(r'^(?P<account_id>[0-9]+)/edit/?$', views.edit, name='edit'),
  url(r'^(?P<account_id>[0-9]+)/update/?$', views.update, name='update'),
  url(r'^new/?$', views.new, name='new'),
  url(r'^create/?$', views.create, name='create'),
  url(r'^create_transaction/?$', views.create_transaction, name='create_transaction'),
]

envelopes/urls.py
from django.conf.urls import url

from . import views

app_name = 'envelopes'
urlpatterns = [
  url(r'^(?P<pk>[0-9]+)/?$', views.DetailView.as_view(), name='detail'),
  url(r'^(?P<envelope_id>[0-9]+)/edit/?$', views.edit, name='edit'),
  url(r'^(?P<envelope_id>[0-9]+)/update/?$', views.update, name='update'),
  url(r'^new/?$', views.new, name='new'),
  url(r'^create/?$', views.create, name='create'),
  url(r'^create_transaction/?$', views.create_transaction, name='create_transaction'),
  url(r'^refill/?$', views.refill, name='refill'),
]

home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
  url(r'^create_transaction/$', views.create_transaction, name='create_transaction'),
  url(r'^refill/$', views.refill, name='refill'),
  url(r'^', views.home, name='home'),
]

money/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from accounts import views as account_views
from envelopes import views as envelope_views
from transactions import views as transaction_views

urlpatterns = [
  url(r'^login/$', auth_views.login, {'template_name': 'shared/login.html'}, name='login'),
  url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
  url(r'^accounts/', include('accounts.urls')),
  url(r'^accounts', account_views.IndexView.as_view(), name='accounts'),
  url(r'^envelopes/', include('envelopes.urls')),
  url(r'^envelopes', envelope_views.IndexView.as_view(), name='envelopes'),
  url(r'^transactions/', include('transactions.urls')),
  url(r'^transactions', transaction_views.IndexView.as_view(), name='transactions'),
  url(r'^admin/', admin.site.urls),
  url(r'^home/', include('home.urls')),
  url(r'^', include('home.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Account(models.Model):
  user    = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
  name    = models.CharField(max_length=50)
  balance = models.DecimalField(default=0, max_digits=8, decimal_places=2)

  def __str__(self):
    return self.name

transactions/models.py
from django.db import models
from accounts.models import Account

class Transaction(models.Model):
  account  = models.ForeignKey(Account, on_delete=models.CASCADE)
  envelope = models.ForeignKey('envelopes.Envelope', on_delete=models.CASCADE, null=True, default=None)
  date     = models.DateField()
  amount   = models.DecimalField(default=0, max_digits=8, decimal_places=2)

  class Meta:
    ordering = ['-date']

  def __str__(self):
    return self.date.isoformat()

  def save(self, *args, **kwargs):
    result = super(Transaction, self).save(*args, **kwargs)
    if self.envelope:
      self.envelope.calculate_transaction_velocity()

    return result

accounts/forms.py
from django.forms import ModelForm
from .models import Account

class AccountForm(ModelForm):
  class Meta:
    model = Account
    fields = ['name']

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from .models import Account
from .forms import AccountForm
from envelopes.models import Envelope
from transactions.models import Transaction

class IndexView(LoginRequiredMixin, generic.ListView):
  template_name = 'accounts/index.html'
  context_object_name = 'all_accounts'

  def get_queryset(self):
    return Account.objects.filter(user_id=self.request.user.id).order_by('name')

  def get_context_data(self, **kwargs):
    context = super(IndexView, self).get_context_data(**kwargs)
    context['all_envelopes'] = Envelope.objects.filter(user_id=self.request.user.id).order_by('name')
    return context

class DetailView(LoginRequiredMixin, generic.DetailView):
  model = Account
  template_name = 'accounts/detail.html'

  def get(self, request, *args, **kwargs):
    try:
      self.object = self.get_object()
    except:
      raise Http404('Not found')

    if self.object.user_id != request.user.id:
      raise Http404('Not found')

    context = self.get_context_data(object=self.object)
    return self.render_to_response(context)

  def get_context_data(self, **kwargs):
    user_id = self.request.user.id
    context = super(DetailView, self).get_context_data(**kwargs)
    context['all_accounts']  = Account.objects.filter(user_id=user_id).order_by('name')
    context['all_envelopes'] = Envelope.objects.filter(user_id=user_id).order_by('name')
    return context

@login_required
def create_transaction(request):
  account = get_object_or_404(Account, pk=request.POST['account_id'])
  envelope = get_object_or_404(Envelope, pk=request.POST['envelope_id'])
  amount = request.POST['amount']
  if 'subtract' in request.POST:
    amount = float(amount) * -1.00

  try:
    transaction = Transaction(account=account, envelope=envelope, date=request.POST['date'], amount=amount)
  except (KeyError):
    messages.add_message(request, messages.ERROR, 'Something squiffy happened.')
    return render(request, 'accounts/index.html')
  else:
    transaction.save()
    messages.add_message(request, messages.SUCCESS, 'Transaction added.')
    return HttpResponseRedirect(reverse('accounts:detail', args=(account.id,)))

@login_required
def new(request):
  context = {
    'title': 'new account',
    'form': AccountForm(),
  }
  return render(request, 'accounts/new.html', context)

@login_required
def create(request):
  form = AccountForm(request.POST)
  if form.is_valid():
    account = Account.objects.create(name=request.POST.get('name'), user_id=request.user.id)
    messages.add_message(request, messages.SUCCESS, account.name + ' created.')
    return HttpResponseRedirect(reverse('accounts:detail', args=(account.id,)))
  else:
    context = {
      'title': 'new account',
      'form': form,
    }
    messages.add_message(request, messages.ERROR, 'Something squiffy happened.')
    return render(request, 'accounts/new.html', context)

@login_required
def edit(request, account_id):
  try:
    account = Account.objects.get(pk=account_id, user_id=request.user.id)
  except:
    raise Http404('Not found')

  title   = ' '.join(['editing', account.name ])
  form    = AccountForm(instance=account)
  context = {
    'title': title,
    'account': account,
    'form': form,
  }
  return render(request, 'accounts/edit.html', context)

@login_required
def update(request, account_id):
  try:
    account = Account.objects.get(pk=account_id, user_id=request.user.id)
  except:
    raise Http404('Not found')

  form = AccountForm(request.POST)
  if form.is_valid():
    account.name = request.POST.get('name', account.name)
    account.save()
    messages.add_message(request, messages.SUCCESS, account.name + ' updated.')
    return HttpResponseRedirect(reverse('accounts:detail', args=(account.id,)))
  else:
    title = ' '.join(['editing', account.name ])
    context = {
      'title': title,
      'account': account,
      'form': form,
    }
    messages.add_message(request, messages.ERROR, 'Something squiffy happened.')
    return render(request, 'accounts/edit.html', context)

accounts/templates/accounts/detail.html
{% extends 'shared/base.html' %}
{% block title %} {{ account.name }} {% endblock %}
{% load static %}
{% load currency %}

{% block main %}
  <h1>
    <a href="{% url 'accounts' %}">all accounts</a>
    &raquo;
    {{ account.name|lower }}
    <a title="edit {{ account.name }}" class="icon edit account" href="{% url 'accounts:edit' account.id %}"></a>
  </h1>
  <h2>
    balance
    <span class="{% if account.balance > 0 %}fnt--green{% else %}fnt--red{% endif %}">{{ account.balance|currency }}</span>
  </h2>
  <table>
    <thead>
      <tr>
        <th>date</th>
        <th>envelope</th>
        <th class="txt--right">amount</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in account.transaction_set.all %}
      <tr>
        <td>{{ transaction }}</td>
        <td>
          {% if transaction.envelope_id %}
          <a href="{% url 'envelopes:detail' transaction.envelope_id %}">{{ transaction.envelope }}</a>
          {% else %}
          -
          {% endif %}
        </td>
        <td class="txt--right {% if transaction.amount > 0 %}fnt--green{% else %}fnt--red{% endif %}">{{ transaction.amount|currency }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

{% block aside %}
  <aside class="grd-row-col-2-6">
    <form action="{% url 'accounts:create_transaction' %}" method="post" class="brdr--light-gray">
      {% include 'shared/partials/transaction_form.html' with all_accounts=all_accounts all_envelopes=all_envelopes account_id=account.id %}
    </form>
  </aside>
{% endblock %}

accounts/templates/accounts/edit.html
{% extends 'shared/base.html' %}
{% block title %} {{ title }} {% endblock %}
{% load static %}

{% block main %}
  <h1>
    <a href="{% url 'accounts' %}">all accounts</a>
    &raquo;
    <a href="{% url 'accounts:detail' account.id %}">{{ account.name|lower }}</a>
    &raquo;
    edit
  </h1>
  <form action="{% url 'accounts:update' account.id %}" method="post">
    {% include 'partials/account_form.html' with form=form %}
  </form>
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'shared/base.html' %}
{% block title %} accounts {% endblock %}
{% load static %}
{% load currency %}

{% block main %}
  <h1>
    all accounts
    <a title="new account" class="icon new account" href="{% url 'accounts:new' %}"></a>
  </h1>
  {% if all_accounts %}
  <table>
    <thead>
      <tr>
        <th>name</th>
        <th class="txt--right">balance</th>
      </tr>
    </thead>
    <tbody>
      {% for account in all_accounts %}
      <tr>
        <td><a href="{% url 'accounts:detail' account.id %}">{{ account }}</a></td>
        <td class="txt--right {% if account.balance > 0 %}fnt--green{% else %}fnt--red{% endif %}">{{ account.balance|currency }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}
{% endblock %}

{% block aside %}
  <aside class="grd-row-col-2-6">
    <form action="{% url 'accounts:create_transaction' %}" method="post" class="brdr--light-gray">
      {% include 'shared/partials/transaction_form.html' with all_accounts=all_accounts all_envelopes=all_envelopes %}
    </form>
  </aside>
{% endblock %}

accounts/templates/accounts/new.html
{% extends 'shared/base.html' %}
{% block title %} {{ title }} {% endblock %}
{% load static %}

{% block main %}
  <h1>
    <a href="{% url 'accounts' %}">all accounts</a>
    &raquo;
    {{ title }}
  </h1>
  <form action="{% url 'accounts:create' %}" method="post">
    {% include 'partials/account_form.html' with form=form %}
  </form>
{% endblock %}