accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'
urlpatterns = [
  url(r'^(?P<pk>[0-9]+)/?$', views.DetailView.as_view(), name='detail'),
  url(r'^(?P<account_id>[0-9]+)/edit/?$', views.edit, name='edit'),
  url(r'^(?P<account_id>[0-9]+)/update/?$', views.update, name='update'),
  url(r'^new/?$', views.new, name='new'),
  url(r'^create/?$', views.create, name='create'),
  url(r'^create_transaction/?$', views.create_transaction, name='create_transaction'),
]

envelopes/urls.py
from django.conf.urls import url

from . import views

app_name = 'envelopes'
urlpatterns = [
  url(r'^(?P<pk>[0-9]+)/?$', views.DetailView.as_view(), name='detail'),
  url(r'^(?P<envelope_id>[0-9]+)/edit/?$', views.edit, name='edit'),
  url(r'^(?P<envelope_id>[0-9]+)/update/?$', views.update, name='update'),
  url(r'^new/?$', views.new, name='new'),
  url(r'^create/?$', views.create, name='create'),
  url(r'^create_transaction/?$', views.create_transaction, name='create_transaction'),
  url(r'^refill/?$', views.refill, name='refill'),
]

home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
  url(r'^create_transaction/$', views.create_transaction, name='create_transaction'),
  url(r'^refill/$', views.refill, name='refill'),
  url(r'^', views.home, name='home'),
]

money/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from accounts import views as account_views
from envelopes import views as envelope_views
from transactions import views as transaction_views

urlpatterns = [
  url(r'^login/$', auth_views.login, {'template_name': 'shared/login.html'}, name='login'),
  url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
  url(r'^accounts/', include('accounts.urls')),
  url(r'^accounts', account_views.IndexView.as_view(), name='accounts'),
  url(r'^envelopes/', include('envelopes.urls')),
  url(r'^envelopes', envelope_views.IndexView.as_view(), name='envelopes'),
  url(r'^transactions/', include('transactions.urls')),
  url(r'^transactions', transaction_views.IndexView.as_view(), name='transactions'),
  url(r'^admin/', admin.site.urls),
  url(r'^home/', include('home.urls')),
  url(r'^', include('home.urls')),
]

envelopes/models.py
from django.db import models
from django.contrib.auth.models import User
from decimal import Decimal
from transactions.models import Transaction
from datetime import datetime, timedelta

class Envelope(models.Model):
  user                 = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
  name                 = models.CharField(max_length=50)
  monthly_budget       = models.DecimalField(default=0, max_digits=8, decimal_places=2)
  immutable_budget     = models.BooleanField(default=True)
  transaction_velocity = models.DecimalField(default=0, max_digits=18, decimal_places=6)

  def __str__(self):
    return self.name

  def running_total(self):
    if self.transaction_set.count() < 1:
      return self.monthly_budget

    total = 0
    for transaction in self.transaction_set.all():
      total = total - ( -1 * Decimal(transaction.amount) )

    return total

  def calculate_transaction_velocity(self):
    if self.transaction_set.count() < 1:
      return 0

    limit    = datetime.now() - timedelta(days=90)
    total    = Transaction.objects.filter(envelope_id=self.id,date__gt=limit).aggregate(models.Sum('amount'))
    velocity = total['amount__sum'] / 90

    self.transaction_velocity = velocity
    self.save()

    return velocity

  @classmethod
  def refill(cls, date, account, envelopes, amount, immutable=None):
    if len(envelopes) < 1:
      raise ValueError('No envelopes to be filled.')

    ratio = 1.0
    total = 0.0

    for envelope in envelopes:
      total += float(envelope.monthly_budget)

    if total > amount:
      if immutable:
        raise ValueError('Not enough funds to refill the given envelopes.')
      else:
        ratio = amount / total

    transactions = 0
    for envelope in envelopes:
      transaction_amount = round(float(envelope.monthly_budget)*ratio, 2)
      if transaction_amount > 0.0:
        amount -= transaction_amount
        transaction = Transaction(account=account, envelope=envelope, date=date, amount=transaction_amount)
        transaction.save()
        transactions += 1

    if amount > 0.0:
      transaction = Transaction(account=account, date=date, amount=round(amount, 2))
      transaction.save()
      transactions += 1

    return transactions

transactions/models.py
from django.db import models
from accounts.models import Account

class Transaction(models.Model):
  account  = models.ForeignKey(Account, on_delete=models.CASCADE)
  envelope = models.ForeignKey('envelopes.Envelope', on_delete=models.CASCADE, null=True, default=None)
  date     = models.DateField()
  amount   = models.DecimalField(default=0, max_digits=8, decimal_places=2)

  class Meta:
    ordering = ['-date']

  def __str__(self):
    return self.date.isoformat()

  def save(self, *args, **kwargs):
    result = super(Transaction, self).save(*args, **kwargs)
    if self.envelope:
      self.envelope.calculate_transaction_velocity()

    return result

envelopes/forms.py
from django.forms import ModelForm
from .models import Envelope

class EnvelopeForm(ModelForm):
  class Meta:
    model = Envelope
    fields = ['name', 'monthly_budget', 'immutable_budget']

envelopes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from .models import Envelope
from .forms import EnvelopeForm
from accounts.models import Account
from transactions.models import Transaction

class IndexView(LoginRequiredMixin, generic.ListView):
  template_name       = 'envelopes/index.html'
  context_object_name = 'all_envelopes'

  def get_queryset(self):
    return Envelope.objects.filter(user_id=self.request.user.id).order_by('name')

  def get_context_data(self, **kwargs):
    context = super(IndexView, self).get_context_data(**kwargs)
    context['all_accounts']          = Account.objects.filter(user_id=self.request.user.id).order_by('name')
    context['envelope_budget_total'] = 0.0
    context['remaining_total']       = 0.0

    all_envelopes = self.get_queryset()
    for envelope in all_envelopes:
      context['envelope_budget_total'] = context['envelope_budget_total'] + float(envelope.monthly_budget)
      context['remaining_total']       = context['remaining_total'] + float(envelope.running_total())

    return context

class DetailView(LoginRequiredMixin, generic.DetailView):
  model         = Envelope
  template_name = 'envelopes/detail.html'

  def get(self, request, *args, **kwargs):
    try:
      self.object = self.get_object()
    except:
      raise Http404('Not found')

    if self.object.user_id != request.user.id:
      raise Http404('Not found')

    context = self.get_context_data(object=self.object)
    return self.render_to_response(context)

  def get_context_data(self, **kwargs):
    user_id = self.request.user.id
    context = super(DetailView, self).get_context_data(**kwargs)
    context['all_accounts']  = Account.objects.filter(user_id=user_id).order_by('name')
    context['all_envelopes'] = Envelope.objects.filter(user_id=user_id).order_by('name')
    return context

@login_required
def create_transaction(request):
  user_id = request.user.id
  try:
    account  = Account.objects.get(pk=request.POST['account_id'], user_id=user_id)
    envelope = Envelope.objects.get(pk=request.POST['envelope_id'], user_id=user_id)
  except:
    raise Http404('Not found')

  amount = float(request.POST['amount'])
  if 'subtract' in request.POST:
    amount = amount * -1.00

  try:
    transaction = Transaction(account=account, envelope=envelope, date=request.POST['date'], amount=amount)
  except (KeyError):
    messages.add_message(request, messages.ERROR, 'Something squiffy happened.')
    return render(request, 'envelopes/index.html')
  else:
    transaction.save()
    messages.add_message(request, messages.SUCCESS, 'Transaction added.')
    return HttpResponseRedirect(reverse('envelopes:detail', args=(envelope.id,)))

@login_required
def refill(request):
  user_id = request.user.id
  try:
    account = Account.objects.get(pk=request.POST['account_id'], user_id=user_id)
  except:
    raise Http404('Not found')

  amount = float(request.POST['amount'])
  envelope_budget_total           = 0.0
  envelope_immutable_budget_total = 0.0
  immutable_budget_envelopes      = Envelope.objects.filter(user_id=user_id).filter(immutable_budget=True)

  if len(immutable_budget_envelopes):
    for envelope in immutable_budget_envelopes:
      envelope_immutable_budget_total += float(envelope.monthly_budget)

    remaining_envelopes = Envelope.objects.filter(user_id=user_id).filter(immutable_budget=False)
    amount -= envelope_immutable_budget_total

    try:
      count = Envelope.refill(request.POST['date'], account, immutable_budget_envelopes, envelope_immutable_budget_total, True)
      count += Envelope.refill(request.POST['date'], account, remaining_envelopes, amount, False)
    except ValueError as e:
      messages.add_message(request, messages.ERROR, str(e))
      return HttpResponseRedirect(reverse('envelopes'))

  else:
    all_envelopes = Envelope.objects.all()
    try:
      count = Envelope.refill(request.POST['date'], account, all_envelopes, amount, False)
    except ValueError as e:
      messages.add_message(request, messages.ERROR, str(e))
      return HttpResponseRedirect(reverse('envelopes'))

  if count == 1:
    plural = 'transaction'
  else:
    plural = 'transactions'

  messages.add_message(request, messages.SUCCESS, 'Refill successful - ' + str(count) + ' ' + plural + ' added.')
  return HttpResponseRedirect(reverse('envelopes'))

@login_required
def new(request):
  context = {
    'title': 'new envelope',
    'form': EnvelopeForm(),
  }
  return render(request, 'envelopes/new.html', context)

@login_required
def create(request):
  form = EnvelopeForm(request.POST)
  if form.is_valid():
    immutable_budget = False
    if request.POST.get('immutable_budget', False):
      immutable_budget = True
    envelope = Envelope.objects.create(name=request.POST.get('name'), immutable_budget=immutable_budget, monthly_budget=request.POST.get('monthly_budget'), user_id=request.user.id)
    messages.add_message(request, messages.SUCCESS, envelope.name + ' created.')
    return HttpResponseRedirect(reverse('envelopes:detail', args=(envelope.id,)))
  else:
    context = {
      'title': 'new envelope',
      'form': form,
    }
    messages.add_message(request, messages.ERROR, 'Something squiffy happened.')
    return render(request, 'envelopes/new.html', context)

@login_required
def edit(request, envelope_id):
  try:
    envelope = Envelope.objects.get(pk=envelope_id, user_id=request.user.id)
  except:
    raise Http404('Not found')

  title    = ' '.join(['editing', envelope.name ])
  form     = EnvelopeForm(instance=envelope)
  context  = {
    'title': title,
    'envelope': envelope,
    'form': form,
  }
  return render(request, 'envelopes/edit.html', context)

@login_required
def update(request, envelope_id):
  try:
    envelope = Envelope.objects.get(pk=envelope_id, user_id=request.user.id)
  except:
    raise Http404('Not found')

  form = EnvelopeForm(request.POST)
  if form.is_valid():
    envelope.name           = request.POST.get('name', envelope.name)
    envelope.monthly_budget = request.POST.get('monthly_budget', envelope.monthly_budget)
    immutable_budget = False
    if request.POST.get('immutable_budget', False):
      immutable_budget = True
    envelope.immutable_budget = immutable_budget
    envelope.save()
    messages.add_message(request, messages.SUCCESS, envelope.name + ' updated.')
    return HttpResponseRedirect(reverse('envelopes:detail', args=(envelope.id,)))
  else:
    title = ' '.join(['editing', envelope.name ])
    context = {
      'title': title,
      'envelope': envelope,
      'form': form,
    }
    messages.add_message(request, messages.ERROR, 'Something squiffy happened.')
    return render(request, 'envelopes/edit.html', context)

envelopes/templates/envelopes/detail.html
{% extends 'shared/base.html' %}
{% block title %} {{ envelope.name }} {% endblock %}
{% load static %}
{% load currency %}

{% block main %}
  <h1>
    <a href="{% url 'envelopes' %}">all envelopes</a>
    &raquo;
    {{ envelope.name|lower }}
    <a class="icon edit envelope" href="{% url 'envelopes:edit' envelope.id %}"></a>
  </h1>
  {% if envelope.immutable_budget %}
  <p>budget cannot be scaled</p>
  {% endif %}
  <h2>
    running total
    <span class="{% if envelope.running_total > 0 %}fnt--green{% else %}fnt--red{% endif %}">{{ envelope.running_total|currency }}</span>
  </h2>
  <table>
    <thead>
      <tr>
        <th>date</th>
        <th>account</th>
        <th class="txt--right">amount</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in envelope.transaction_set.all %}
      <tr>
        <td>{{ transaction }}</td>
        <td><a href="{% url 'accounts:detail' transaction.account_id %}">{{ transaction.account }}</a></td>
        <td class="txt--right {% if transaction.amount > 0 %}fnt--green{% else %}fnt--red{% endif %}">{{ transaction.amount|currency }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}
{% block aside %}
  <aside class="grd-row-col-2-6">
    <form action="{% url 'envelopes:create_transaction' %}" method="post" class="brdr--light-gray">
      {% include 'shared/partials/transaction_form.html' with all_accounts=all_accounts all_envelopes=all_envelopes envelope_id=envelope.id %}
    </form>
  </aside>
{% endblock %}

envelopes/templates/envelopes/edit.html
{% extends 'shared/base.html' %}
{% block title %} {{ title }} {% endblock %}
{% load static %}

{% block main %}
  <h1>
    <a href="{% url 'envelopes' %}">all envelopes</a>
    &raquo;
    <a href="{% url 'envelopes:detail' envelope.id %}">{{ envelope.name|lower }}</a>
    &raquo;
    edit
  </h1>
  <form action="{% url 'envelopes:update' envelope.id %}" method="post">
    {% include 'partials/envelope_form.html' with form=form %}
  </form>
{% endblock %}

envelopes/templates/envelopes/index.html
{% extends 'shared/base.html' %}
{% block title %} envelopes {% endblock %}
{% load static %}
{% load currency %}

{% block main %}
  <h1>
    all envelopes
    <a title="new envelope" class="icon new envelope" href="{% url 'envelopes:new' %}"></a>
  </h1>
  {% if all_envelopes %}
  <table>
    <thead>
      <tr>
        <th></th>
        <th class="txt--right">monthly budget</th>
        <th class="txt--right">immutable budget?</th>
        <th class="txt--right">remaining</th>
      </tr>
    </thead>
    <tbody>
      {% for envelope in all_envelopes %}
      <tr>
        <td><a href="{% url 'envelopes:detail' envelope.id %}">{{ envelope }}</a></td>
        <td class="txt--right fnt--orange">{{ envelope.monthly_budget|currency }}</td>
        {% if envelope.immutable_budget %}
        <td class="txt--right fnt--green">&#10004;</td>
        {% else %}
        <td class="txt--right fnt--red">&#10008;</td>
        {% endif %}
        <td class="txt--right {% if envelope.running_total >= envelope.monthly_budget %} fnt--green {% else %} fnt--red {% endif %}">{{ envelope.running_total|currency }}</td>
      </tr>
      {% endfor %}
    </tbody>
    <tfoot>
      <tr>
        <td></td>
        <td class="fnt--orange">{{ envelope_budget_total|currency }}</td>
        <td>&nbsp;</td>
        <td class="{% if remaining_total > 0 %}fnt--green{% else %}fnt--red{% endif %}">{{ remaining_total|currency }}</td>
      </tr>
    </tfoot>
  </table>
  {% endif %}
{% endblock %}

{% block aside %}
  <aside class="grd-row-col-2-6">
    <form action="{% url 'envelopes:create_transaction' %}" method="post" class="brdr--light-gray">
      {% include 'shared/partials/transaction_form.html' with all_accounts=all_accounts all_envelopes=all_envelopes %}
    </form>
    <br />
    <form action="{% url 'envelopes:refill' %}" method="post" class="brdr--light-gray">
      {% include 'shared/partials/refill_form.html' with all_accounts=all_accounts %}
    </form>
  </aside>
{% endblock %}

envelopes/templates/envelopes/new.html
{% extends 'shared/base.html' %}
{% block title %} {{ title }} {% endblock %}
{% load static %}

{% block main %}
  <h1>
    <a href="{% url 'envelopes' %}">all envelopes</a>
    &raquo;
    {{ title }}
  </h1>
  <form action="{% url 'envelopes:create' %}" method="post">
    {% include 'partials/envelope_form.html' with form=form %}
  </form>
{% endblock %}